name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/UserAPI - Test Suite.json" -e "29574936-f93d95d8-94c9-4011-8459-bdabba836b12" --integration-id "162690-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint af36bf45-c459-4509-8986-ef8af3d233ca --integration-id 162690
